language: android\
jdk: oraclejdk8
android:
  components:
     - tools
     - platform-tools
     - build-tools-28.0.3
     - android-28
     - extra-google-google_play_services
     - extra-google-m2repository
     - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26


  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

  before_install:
    - chmod +x gradlew